title: link-styler
description: link-styler is a JavaScript package that helps you find links in text and replace them with a tag that has custom styling.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
